# Generated by Django 4.2.10 on 2024-03-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
    ]
