# Generated by Django 4.2.10 on 2024-03-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_followrequest_accepted"),
        ("user_activity", "0002_alter_comment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="accounts.profile",
            ),
        ),
    ]
