# Generated by Django 4.2.10 on 2024-03-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_activity", "0003_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
    ]
