# Generated by Django 4.2.10 on 2024-03-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("direct", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="reciever",
            new_name="receiver",
        ),
    ]
