# Generated by Django 4.2.10 on 2024-03-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("direct", "0002_rename_reciever_message_receiver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="media created"
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                ("video_file", models.FileField(upload_to="Post/Media/viedo/")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="direct.message",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="media created"
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="Message/Media/image/")),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="direct.message",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="media created"
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                ("audio_file", models.FileField(upload_to="Post/Media/audio/")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audios",
                        to="direct.message",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
                "abstract": False,
            },
        ),
    ]
