# Generated by Django 4.2.10 on 2024-03-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("direct", "0003_video_image_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio",
                to="direct.message",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="direct.message",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="direct.message",
            ),
        ),
    ]
