# Generated by Django 4.2.10 on 2024-03-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birthday",
        ),
    ]
