# Generated by Django 4.2.10 on 2024-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_followrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="followrequest",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
