# Generated by Django 4.2.10 on 2024-03-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_profile_birthday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="updated_at",
        ),
    ]
