# Generated by Django 4.2.10 on 2024-03-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_followrequest_accepted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="followrequest",
            name="accepted",
        ),
    ]
