# Generated by Django 4.2.10 on 2024-03-02 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_profile_follower_profile_following_delete_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="following",
        ),
        migrations.AddField(
            model_name="profile",
            name="follower",
            field=models.ManyToManyField(
                null=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                null=True, related_name="followings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
