# Generated by Django 4.2.10 on 2024-03-02 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0006_remove_profile_follower_remove_profile_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="follower",
            field=models.ManyToManyField(
                related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                related_name="followings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
