# Generated by Django 4.2.10 on 2024-03-02 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0007_alter_profile_follower_alter_profile_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
