# Generated by Django 4.2.10 on 2024-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_remove_post_like_remove_post_mention_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewer",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
