# Generated by Django 4.2.10 on 2024-03-07 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_viewprofile"),
        ("content", "0004_alter_post_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyviewer",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="viewer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewers_of_post",
                to="accounts.profile",
            ),
        ),
    ]
