# Generated by Django 4.2.10 on 2024-03-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_viewer_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewer",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
