# Generated by Django 4.2.10 on 2024-03-07 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_rename_viewer_viewerpost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="viewerpost",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterUniqueTogether(
            name="viewerpost",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="viewerpost",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="viewerpost",
            name="count",
        ),
    ]
