# Generated by Django 4.2.10 on 2024-03-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_viewerpost_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="viewerpost",
            options={},
        ),
        migrations.RemoveField(
            model_name="viewerpost",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="viewerpost",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="viewerpost",
            name="updated_at",
        ),
    ]
