# Generated by Django 4.2.10 on 2024-03-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_viewer_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="owner",
        ),
    ]
