# Generated by Django 4.2.10 on 2024-03-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_alter_viewerpost_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewerpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_viewed",
                to="content.post",
            ),
        ),
    ]
