# Generated by Django 4.2.10 on 2024-03-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_alter_like_post_alter_like_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/content/post/",
                verbose_name="media of post",
            ),
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_media",
                to="content.post",
                verbose_name="post",
            ),
        ),
    ]
